services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"

  elastic-search:
    image: elasticsearch:8.8.0
    restart: always
    environment:
      - discovery.type=single-node
      - xpack-security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"